discourse_lottery:
  discourse_lottery_enabled:
    default: false
    client: true
  discourse_lottery_allowed_on_groups:
    client: true
    type: group_list
    list_type: compact
    default: ""
    allow_any: false
    refresh: true
