plugins:
  lottery_enabled:
    default: false
    client: true
  lottery_min_participants_global:
    default: 5
    min: 1
    max: 100
    client: true
  lottery_post_lock_delay_minutes:
    default: 60
    min: 0
    max: 1440
